FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
WORKDIR /
COPY . .
RUN rm -r Pork.Manager
RUN dotnet restore Pork.Controller/Pork.Controller.csproj
RUN dotnet publish Pork.Controller -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /publish
COPY --from=build-env /publish .
ENV ASPNETCORE_URLS=http://+:9092
ENTRYPOINT ["dotnet", "Pork.Controller.dll"]